#!/bin/bash
# Quick Testing Guide for Willy Collection E-commerce Platform
# Run this script to verify all systems are working correctly

echo "🧪 Willy Collection System Test Guide"
echo "======================================"
echo ""

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "📋 Pre-Test Checklist:"
echo "✓ Backend running on port 4000"
echo "✓ Frontend running on port 3000"
echo "✓ Database initialized"
echo ""

echo "🔍 Manual Testing Scenarios:"
echo ""

echo "1️⃣  HOMEPAGE & NAVIGATION"
echo "   □ Visit http://localhost:3000"
echo "   □ Verify hero carousel loads and auto-plays"
echo "   □ View trending section with 12 products"
echo "   □ Click header logo to return home"
echo "   □ Verify footer links are functional"
echo ""

echo "2️⃣  DARK MODE"
echo "   □ Click sun/moon icon in header"
echo "   □ Verify page transitions to dark mode"
echo "   □ Check all components render correctly in dark mode:"
echo "     - Forms and inputs"
echo "     - Cards and buttons"
echo "     - Navigation"
echo "     - Footer"
echo "   □ Refresh page - dark mode preference persists"
echo ""

echo "3️⃣  PRODUCT DISCOVERY"
echo "   □ Browse products by category (/categories/:category)"
echo "   □ Search for 'nike' in search bar"
echo "   □ Click on product card to view details"
echo "   □ Check product details page loads correctly:"
echo "     - Product images visible"
echo "     - Size selector available"
echo "     - Price and stock information displayed"
echo ""

echo "4️⃣  ADD TO CART"
echo "   □ From product details, select a size"
echo "   □ Click 'Add to Cart'"
echo "   □ Verify cart count updates in header"
echo "   □ Navigate to /cart"
echo "   □ Verify item appears with correct size"
echo "   □ Modify quantity"
echo "   □ Remove item"
echo ""

echo "5️⃣  CHECKOUT (CASH)"
echo "   □ Add items to cart"
echo "   □ Go to /checkout"
echo "   □ Fill in form:"
echo "     - Name: Test User"
echo "     - Phone: 0797062606"
echo "     - Location: Test Location"
echo "   □ Select 'Cash on Delivery'"
echo "   □ Click 'Place Order'"
echo "   □ Verify success message"
echo "   □ Cart clears"
echo ""

echo "6️⃣  CHECKOUT (MPESA - Requires credentials)"
echo "   □ Add items to cart"
echo "   □ Go to /checkout"
echo "   □ Fill in form with test data"
echo "   □ Select 'M-Pesa'"
echo "   □ Enter MPESA number"
echo "   □ Click 'Pay with M-Pesa'"
echo "   □ Monitor payment status polling"
echo ""

echo "7️⃣  FORM VALIDATION"
echo "   □ Try submitting checkout with empty fields"
echo "   □ Verify validation messages appear"
echo "   □ Check form fields are in dark mode if enabled"
echo "   □ Verify focus states have accent color ring"
echo ""

echo "8️⃣  SEARCH & FILTERING"
echo "   □ Use search bar to find 'jordan'"
echo "   □ Verify search results appear"
echo "   □ Use category filter"
echo "   □ Verify filtered results display correctly"
echo ""

echo "9️⃣  RESPONSIVE DESIGN"
echo "   □ Test on mobile viewport (DevTools)"
echo "   □ Verify navigation works on mobile"
echo "   □ Check product grid responsive"
echo "   □ Verify forms stack properly on mobile"
echo "   □ Test landscape orientation"
echo ""

echo "🔟  PERFORMANCE"
echo "   □ Run stress-test: node stress-test.js"
echo "   □ Monitor response times (should average ~120ms)"
echo "   □ Check throughput (should be 20+ req/s)"
echo "   □ Verify success rate (target >95% for local testing)"
echo ""

echo "📱 MOBILE TESTING"
echo "   □ Test on actual mobile device"
echo "   □ Verify touch interactions work smoothly"
echo "   □ Check button sizes are mobile-friendly"
echo "   □ Verify forms are easy to fill on mobile"
echo ""

echo "🔐 SECURITY CHECKS"
echo "   □ Open DevTools Network tab"
echo "   □ Verify no sensitive data in localStorage"
echo "   □ Check API requests have correct headers"
echo "   □ Ensure POST/PUT requests include proper CORS headers"
echo ""

echo "❌ ERROR HANDLING"
echo "   □ Try accessing non-existent product (/sneakers/invalid-slug)"
echo "   □ Verify 404 error displays gracefully"
echo "   □ Check network error handling in cart operations"
echo "   □ Verify form errors display properly"
echo ""

echo "✨ BROWSER COMPATIBILITY"
echo "   □ Test in Chrome (Latest)"
echo "   □ Test in Firefox (Latest)"
echo "   □ Test in Safari (Latest)"
echo "   □ Test in Edge (Latest)"
echo ""

echo ""
echo "📊 PERFORMANCE BENCHMARKS"
echo "────────────────────────"
echo "Target: Average response time < 200ms"
echo "Target: Throughput > 20 req/s"
echo "Target: Success rate > 95%"
echo ""

echo "🚀 Ready to test! Start with:"
echo "   cd /path/to/frontend && npm run dev"
echo "   cd /path/to/backend && npm run dev"
echo ""

echo "💡 Tips:"
echo "   - Use Ctrl+Shift+J to open DevTools console"
echo "   - Check Network tab for API latency"
echo "   - Use Lighthouse for full performance audit"
echo "   - Test with various network speeds (DevTools > Network)"
echo ""
